"""seed test data

Revision ID: a315fc2d4af8
Revises: 9af3b6fc91e6
Create Date: 2026-02-18 17:50:58.665069

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a315fc2d4af8"
down_revision: Union[str, Sequence[str], None] = "9af3b6fc91e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    op.execute(
        sa.text(
            "INSERT INTO public.base_user (id, full_name, email_address, password_hash, type) VALUES (1, 'Test User', 'user@test.com', '$2b$12$rtDgQ9sHejRPAd2osIEDTuY8QEwP8oQwgQaJxfquhJMlLMxFvvsme', 'user');"
        )
    )
    op.execute(
        sa.text(
            "INSERT INTO public.base_user (id, full_name, email_address, password_hash, type) VALUES (2, 'System Administrator', 'admin@test.com', '$2b$12$vqFjXfbOrVfZgiJpEjdEne7sgYVNXaMsGVcIFhxJBg3Iij4/SG6ru', 'admin');"
        )
    )

    op.execute(
        sa.text(
            "INSERT INTO public.account (id, user_id, balance) VALUES (1, 1, 1000.0);"
        )
    )
    op.execute(sa.text("INSERT INTO public.account_user (id) VALUES (1);"))
    op.execute(sa.text("INSERT INTO public.admin_user (id) VALUES (2);"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
